### ISSUE TITLE
Minor issue/improvement

### ISSUE THREAD

**Issue by p-s-vishnu** [schoolofaitvm/play-with-data#1]
1. In Introduction to Python and Data Science.ipynb, the anchor links - "What is data", etc are empty. 

2. I think it will be nice to add -"How to load dataset in Google colab", I have attached a reference to the page but which one is the best way ?

https://colab.research.google.com/notebooks/io.ipynb

**Comment by schoolofaitvm** [comment]
The empty links in the notebook was left blank for the video presentation demonstration, which will be added on. And the second point is a necessary change. Will soon update that!
